### ISSUE TITLE
How do I use these within kinto?

### ISSUE THREAD

**Issue by matthew-gill** [rbreaves/Universal-Keys#2]
I'm so sorry for the complete noob question, but I can't seem to find this in the docs!

I've installed Kinto, which seems to be working well!

However, I'd like to install the keymap you've got here for IntelliJ, but I can't workout how!

**Comment by rbreaves** [comment]
There’s nothing for you to do as IntelliJ has already been added to Kinto.py on line 69 & Kinto.ahk line 211.

For right now I use Universal Keys as a reference to build these out manually, but as this grows I’m surely going to revisit this & automate it.

If you have any issues w/ it or something doesn’t work as expected then please let me know.

https://github.com/rbreaves/kinto/blob/master/xkeysnail-config/kinto.py

https://github.com/rbreaves/kinto/blob/master/windows/kinto.ahk

**Comment by rbreaves** [comment]
Just to note I updated the ahk config yesterday as I discovered a few syntax issues related to the intellij remap - that would have prevented a few remaps from working.

**Comment by matthew-gill** [comment]
Great! Thanks @rbreaves !
